document.addEventListener('DOMContentLoaded',function(){let
field=document.createElement('div'),elements=[],coordElements=[];document.body.appendChild(field);field.classList.add('field');for(let i=0;i<15;i++){let excel=document.createElement('div');elements.push(excel);excel.classList.add('excel')}
if(('ontouchstart' in window)||window.DocumentTouch&&document instanceof DocumentTouch){console.log('this is a touch device')}else{for(let i=0;i<elements.length;i++){elements[i].classList.add('excel_hover')}
console.log('this is not a touch device')}
let excel=document.querySelectorAll('.excel'),noneExcel=document.createElement('div'),x=1,y=1,excelWidth=0,excelHeight=0,noneExcelWidth=373.53,noneExcelHeight=373.8;field.appendChild(noneExcel);noneExcel.classList.add('none-excel');noneExcel.setAttribute('posX',4);noneExcel.setAttribute('posY',4);noneExcel.style.transform=`translate(${noneExcelWidth}px, ${noneExcelHeight}px)`;for(let i=0;i<elements.length;i++){if(y>4){y=1;x++;excelWidth=0;excelHeight+=124.6}
elements[i].setAttribute('posX',x);elements[i].setAttribute('posY',y);elements[i].style.transform=`translate(${excelWidth}px, ${excelHeight}px)`;excelWidth+=124.51;y++}
for(let i=0;i<elements.length;i++){coordElements.push(elements[i].style.transform)}
elements.sort(function(){return Math.random()-0.5});for(let i=0;i<elements.length;i++){elements[i].innerText=i+1;field.appendChild(elements[i])}
let randomElements=document.querySelectorAll('.excel');let coordRandomElements=[];console.log(elements);field.addEventListener('click',function(event){let
target=event.target,targetPosX=+target.getAttribute('posX'),targetPosY=+target.getAttribute('posY'),noneExcelPosX=+noneExcel.getAttribute('posX'),noneExcelPosY=+noneExcel.getAttribute('posY');if(target.classList=='excel'||target.classList=='excel excel_hover'){let
noneExcelPos=noneExcel.style.transform,targetPos=target.style.transform;if(targetPosX==noneExcelPosX&&targetPosY+1==noneExcelPosY){target.style.transform=noneExcelPos;noneExcel.style.transform=targetPos;target.setAttribute('posY',targetPosY+1);noneExcel.setAttribute('posY',noneExcelPosY-1)}else if(targetPosX==noneExcelPosX&&targetPosY-1==noneExcelPosY){target.style.transform=noneExcelPos;noneExcel.style.transform=targetPos;target.setAttribute('posY',targetPosY-1);noneExcel.setAttribute('posY',noneExcelPosY+1)}
if(targetPosX+1==noneExcelPosX&&targetPosY==noneExcelPosY){target.style.transform=noneExcelPos;noneExcel.style.transform=targetPos;target.setAttribute('posX',targetPosX+1);noneExcel.setAttribute('posX',noneExcelPosX-1)}else if(targetPosX-1==noneExcelPosX&&targetPosY==noneExcelPosY){target.style.transform=noneExcelPos;noneExcel.style.transform=targetPos;target.setAttribute('posX',targetPosX-1);noneExcel.setAttribute('posX',noneExcelPosX+1)}
console.log('target X = '+targetPosX);console.log('target Y = '+targetPosY);console.log('excelWidth - '+excelWidth)}
coordRandomElements.splice(0,randomElements.length);for(let i=0;i<elements.length;i++){coordRandomElements.push(randomElements[i].style.transform)}
for(let i=0;i<elements.length;i++){if(JSON.stringify(coordRandomElements)==JSON.stringify(coordElements)){alert('win');break}}});function move(elem,nonePos,pos,axis,targetAxis,noneAxis){}})